### ISSUE TITLE
Dockerfile.arm does not work

### ISSUE THREAD

**Issue by codycompton** [juzam/docker-keybase-build#1] opened 2016-12-30 15:46 UTC
It appears Keybase may have changed their repo structure and Dockerfile.arm no longer compiles successfully. I tried some other paths but nothing worked. Here is the error on Dockerfile.arm as-is:

Step 8 : RUN go get github.com/keybase/client/go/keybase && go build -tags production github.com/keybase/client/go/keybase
 ---> Running in c6a62355186a
package context: unrecognized import path "context"
The command '/bin/sh -c go get github.com/keybase/client/go/keybase && go build -tags production github.com/keybase/client/go/keybase' returned a non-zero code: 1

**Comment by juzam** [comment] 2016-12-30 15:51
I'll try to look into it next week. In the meanwhile could you please try the https://github.com/juzam/docker-keybase-build/blob/master/Dockerfile.xcompile-arm on a x86 machine? 
That should cross compile an arm compatible binary whilst running on an x86 host.

**Comment by codycompton** [comment] 2016-12-30 16:55
That compiled successfully and with some trickery got it from my Windows box to my RPi3. Look forward to seeing what the fix is to get this work direct from the RPi.

**Comment by juzam** [comment] 2017-01-01 15:42
The problem is the Golang version that is included in the current base image `hypriot/rpi-golang` which is `1.6.x`. 
Keybase now requires at least Golang version `1.7` so a new base image is required. 
There is no "official" docker image for arm that has 1.7 AFAIK so we need to roll our own. cloning the official golang dockerfile repository and using https://github.com/docker-library/golang/tree/master/1.7/wheezy one can use the Dockerfile from my gist: https://gist.github.com/juzam/6a5f4eb8ac63ad3f22249af9fc7f22a8 to build the new base image, that can be then used to compile keybase swapping the first line in the current `Dockerfile.arm` with somethig like `FROM: localgolang:armv6l-1.7`.

**Comment by juzam** [comment] 2017-01-01 20:21
I'll rework the repository in order to make it easier to build keybase, no matter what the arch you're running on/compiling for, using `docker-compose` and automating the copy to the local filesystem. I have a POC that works nicely for native arm. It builds the golang image first and then runs the build of keybase. all by issuing a single command: `docker-compose up keybase-native-arm`

**Comment by juzam** [comment] 2017-01-05 09:18
@codycompton I've pushed a branch with the rework based on docker-compose: https://github.com/juzam/docker-keybase-build/tree/docker-compose feedback much appreciated. thank you

**Comment by juzam** [comment] 2017-01-17 17:51
closed via https://github.com/juzam/docker-keybase-build/pull/2

**Closed as completed by juzam** 2017-01-17 17:51 UTC
